---
- name: Ensure /etc/nebula directory exists
  file:
    path: /etc/nebula
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Download & Extract Nebula
  unarchive:
    src: "https://github.com/slackhq/nebula/releases/download/v{{ nebula_version }}/nebula-linux-{{ cpu_arch | default('amd64') }}.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    owner: root
    group: root
    mode: '0700'
    creates: '/usr/local/bin/nebula'
